// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChixUHSpJFXEqa4trgaJZ-KOszbg9spdg',
    appId: '1:248560151060:android:57abe881745cd805b11501',
    messagingSenderId: '248560151060',
    projectId: 'trackify-inurum',
    storageBucket: 'trackify-inurum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKxDMwy9sha5bOKLoiu26uNblRVXgI6Lg',
    appId: '1:248560151060:ios:cc65cf204c149c22b11501',
    messagingSenderId: '248560151060',
    projectId: 'trackify-inurum',
    storageBucket: 'trackify-inurum.firebasestorage.app',
    androidClientId: '248560151060-bgp6pit5jpqesvb3ni5jj1mrv4bq6ij9.apps.googleusercontent.com',
    iosClientId: '248560151060-3niec83ho8cfsder8092elnrupu22n8n.apps.googleusercontent.com',
    iosBundleId: 'com.trackify.mytrackmate.trackify',
  );

}